### ISSUE TITLE
A2D (AIO) isn't available

### ISSUE THREAD

**Issue by bjbeare** [intel-iot-devkit/android-things-samples#18]
AIO isn't available because the Peripheral Manager doesn't support it. We may want to provide a user-level AIO driver for specific SPI connected AIO (or I2C) and handle that without PM support.

**Comment by spitfire88** [comment]
There is a drivers available in UPM that could be used to do that while A2D support is added in PIO. 
A2D over I2C: adc121c021, ads1x15
We should write examples to demonstrate their use in AT.

**Comment by bjbeare** [comment]
I was wondering that. Agreed on an example/driver for this.

**Comment by bjbeare** [comment]
addressed by https://github.com/intel-iot-devkit/android-things-samples/pull/34
